Add AM_CPPFLAGS to makefile.am for waitforx
Without this, the compilation of waitforx can fail on FreeBSD
with this error:-

waitforx.c:1:10: fatal error: 'X11/extensions/Xrandr.h' file not found

This PR makes the use of AM_CPPFLAGS and AM_CFLAGS the same as
that for (e.g.) chansrv which also depends on X includes