xrdp-droppriv erroneous includes
xrdp-droppriv.c is erroneously including os_calls.c rather than
os_calls.h

This leads to a link failure on Ubuntu 20.04:-

/usr/bin/ld: xrdp-droppriv.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'

The error does not happen with later glibc versions, as libdl is
included in libc for these versions.

(cherry picked from commit b914d3e997ee70544db5fd2e28509bbcae32ddc6)